### ISSUE TITLE
Removing redux?

### ISSUE THREAD

**Issue by jeveloper** [commutatus/react-native-boilerplate#2]
Have you considered that ?

Thanks

**Comment by Sathyanarayan09** [comment]
Hi @jeveloper , Added redux because it was a preferred choice for global state management, and it can be easily removed when it's not required.

**Comment by Sathyanarayan09** [comment]
@jeveloper basically if you remove provider from this file below should remove redux from the app.  https://github.com/commutatus/react-native-boilerplate/blob/master/index.js
